### ISSUE TITLE
Ненадежная логика

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/todo-list-react-ts#1]
![image](https://user-images.githubusercontent.com/101792032/179160079-67b9afbb-1365-4d8a-bc9c-3122e47fa857.png)

Зачем эта кнопка сама же отменяет свои эффекты? Пусть она просто отмечает все задачи как выполненные и все. 

Могу показать к какому багу это приводит. Кратко: ведет себя не очевидно

1. делаем задачи а б в
2. Отмечаем все с кнопки
3. Снимаем отметки с а и б
4. удаляем все выполненные (остается а и б)
5. отмечаем все как выполненные с кнопки, **но ничего не происходит** (потому что флаг isMarked висит в true до сих пор)

Этой логики не было в техзадании, так что лучше вырезать. Либо сделай так, чтобы работало нормально

**Comment by VKNagibin** [comment]
Да, я практически сразу понял свою ошибку) в хуках переделал и сюда исправления закинул 8bec58d

**Comment by VKNagibin** [comment]
не тот коммит, вот этот 
c2643e0
