### ISSUE TITLE
Ля че нашел

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/todo-list-react-ts#2]
![image](https://user-images.githubusercontent.com/101792032/179249594-34869f5e-2c05-4813-bcb7-fd589442fb1b.png)
![image](https://user-images.githubusercontent.com/101792032/179249619-ea24230d-ae95-4a45-9964-681248e9afa1.png)

Все работает, а нотация через точку, удобно жы и красиво

https://habr.com/ru/post/673378/

**Comment by VKNagibin** [comment]
Чекал на выходных, супер затянуто, я ничего не поняль) ссыль сохранил, до лучших времён

**Comment by mordvinian** [comment]
Ты можешь делать компоненты частью другого компонента, и тогда будет лучше читаться
