### ISSUE TITLE
Хорошо, только переложи в другое место

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/todo-list-react-ts#3]
![image](https://user-images.githubusercontent.com/101792032/180718844-9a0129bb-548f-417c-ba14-a6e0c2d3e66d.png)

Делать вместо нативных инпутов отдельные компоненты это хорошо. В дальнейшем, мы можем их стилизовать, и это изменится во всем проекте, например.

Только такие вещи нужно хранить отдельно, т.к. они могут использоваться по всему приложению. 
Переложи inputText в отдельную папку primitives

**Comment by VKNagibin** [comment]
вроде done  c6cee1f

**Comment by VKNagibin** [comment]
вроде done c6cee1f
